name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Install and Build Backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build
